repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: format
        name: Run Format Code
        entry: make format
        language: system
        pass_filenames: false
        types: [python]